# Generated by Django 4.0.1 on 2022-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
